#!/bin/bash
set -o pipefail
set -e
rm -f test_query.ml
echo '
#use "topfind"
#require "ch_queries"
#require "ch_queries.ppx"
#use "test_queries.ml"
' > test_query.ml
echo '>>> PREPROCESSING'
echo "$1" | grep -v '^#' | ch_queries_ppx -impl - | ocamlformat --enable-outside-detected-project --name test_query.ml --impl -
echo '>>> RUNNING'
echo "$1" >> test_query.ml
ocaml ./test_query.ml
