#!/bin/bash
rm -f test_query.ml
echo '
#use "topfind"
#require "queries"
#require "queries.ppx"
#use "test_queries.ml"
' > test_query.ml
echo '>>> PREPROCESSING'
echo "$1" | rg -v '^#' | ppx_queries -impl - | ocamlformat --enable-outside-detected-project --name test_query.ml --impl -
echo '>>> RUNNING'
echo "$1" >> test_query.ml
ocaml ./test_query.ml
