lib: [
  "_build/install/default/lib/ch_queries/META"
  "_build/install/default/lib/ch_queries/ch_queries.a"
  "_build/install/default/lib/ch_queries/ch_queries.cma"
  "_build/install/default/lib/ch_queries/ch_queries.cmi"
  "_build/install/default/lib/ch_queries/ch_queries.cmt"
  "_build/install/default/lib/ch_queries/ch_queries.cmti"
  "_build/install/default/lib/ch_queries/ch_queries.cmx"
  "_build/install/default/lib/ch_queries/ch_queries.cmxa"
  "_build/install/default/lib/ch_queries/ch_queries.ml"
  "_build/install/default/lib/ch_queries/ch_queries.mli"
  "_build/install/default/lib/ch_queries/dune-package"
  "_build/install/default/lib/ch_queries/opam"
  "_build/install/default/lib/ch_queries/ppx/ch_queries_ppx.a" {"ppx/ch_queries_ppx.a"}
  "_build/install/default/lib/ch_queries/ppx/ch_queries_ppx.cma" {"ppx/ch_queries_ppx.cma"}
  "_build/install/default/lib/ch_queries/ppx/ch_queries_ppx.cmi" {"ppx/ch_queries_ppx.cmi"}
  "_build/install/default/lib/ch_queries/ppx/ch_queries_ppx.cmt" {"ppx/ch_queries_ppx.cmt"}
  "_build/install/default/lib/ch_queries/ppx/ch_queries_ppx.cmti" {"ppx/ch_queries_ppx.cmti"}
  "_build/install/default/lib/ch_queries/ppx/ch_queries_ppx.cmx" {"ppx/ch_queries_ppx.cmx"}
  "_build/install/default/lib/ch_queries/ppx/ch_queries_ppx.cmxa" {"ppx/ch_queries_ppx.cmxa"}
  "_build/install/default/lib/ch_queries/ppx/ch_queries_ppx.ml" {"ppx/ch_queries_ppx.ml"}
  "_build/install/default/lib/ch_queries/ppx/ch_queries_ppx.mli" {"ppx/ch_queries_ppx.mli"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax.a" {"syntax/ch_queries_syntax.a"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax.cma" {"syntax/ch_queries_syntax.cma"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax.cmi" {"syntax/ch_queries_syntax.cmi"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax.cmt" {"syntax/ch_queries_syntax.cmt"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax.cmx" {"syntax/ch_queries_syntax.cmx"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax.cmxa" {"syntax/ch_queries_syntax.cmxa"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax.ml" {"syntax/ch_queries_syntax.ml"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Eq_class.cmi" {"syntax/ch_queries_syntax__Eq_class.cmi"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Eq_class.cmt" {"syntax/ch_queries_syntax__Eq_class.cmt"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Eq_class.cmti" {"syntax/ch_queries_syntax__Eq_class.cmti"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Eq_class.cmx" {"syntax/ch_queries_syntax__Eq_class.cmx"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Lexer.cmi" {"syntax/ch_queries_syntax__Lexer.cmi"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Lexer.cmt" {"syntax/ch_queries_syntax__Lexer.cmt"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Lexer.cmti" {"syntax/ch_queries_syntax__Lexer.cmti"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Lexer.cmx" {"syntax/ch_queries_syntax__Lexer.cmx"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Loc.cmi" {"syntax/ch_queries_syntax__Loc.cmi"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Loc.cmt" {"syntax/ch_queries_syntax__Loc.cmt"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Loc.cmx" {"syntax/ch_queries_syntax__Loc.cmx"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Parser.cmi" {"syntax/ch_queries_syntax__Parser.cmi"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Parser.cmt" {"syntax/ch_queries_syntax__Parser.cmt"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Parser.cmti" {"syntax/ch_queries_syntax__Parser.cmti"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Parser.cmx" {"syntax/ch_queries_syntax__Parser.cmx"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Printer.cmi" {"syntax/ch_queries_syntax__Printer.cmi"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Printer.cmt" {"syntax/ch_queries_syntax__Printer.cmt"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Printer.cmti" {"syntax/ch_queries_syntax__Printer.cmti"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Printer.cmx" {"syntax/ch_queries_syntax__Printer.cmx"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Syntax.cmi" {"syntax/ch_queries_syntax__Syntax.cmi"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Syntax.cmt" {"syntax/ch_queries_syntax__Syntax.cmt"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Syntax.cmti" {"syntax/ch_queries_syntax__Syntax.cmti"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Syntax.cmx" {"syntax/ch_queries_syntax__Syntax.cmx"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Ulexer.cmi" {"syntax/ch_queries_syntax__Ulexer.cmi"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Ulexer.cmt" {"syntax/ch_queries_syntax__Ulexer.cmt"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Ulexer.cmx" {"syntax/ch_queries_syntax__Ulexer.cmx"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Uparser.cmi" {"syntax/ch_queries_syntax__Uparser.cmi"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Uparser.cmt" {"syntax/ch_queries_syntax__Uparser.cmt"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Uparser.cmti" {"syntax/ch_queries_syntax__Uparser.cmti"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax__Uparser.cmx" {"syntax/ch_queries_syntax__Uparser.cmx"}
  "_build/install/default/lib/ch_queries/syntax/eq_class.ml" {"syntax/eq_class.ml"}
  "_build/install/default/lib/ch_queries/syntax/eq_class.mli" {"syntax/eq_class.mli"}
  "_build/install/default/lib/ch_queries/syntax/lexer.ml" {"syntax/lexer.ml"}
  "_build/install/default/lib/ch_queries/syntax/lexer.mli" {"syntax/lexer.mli"}
  "_build/install/default/lib/ch_queries/syntax/loc.ml" {"syntax/loc.ml"}
  "_build/install/default/lib/ch_queries/syntax/parser.ml" {"syntax/parser.ml"}
  "_build/install/default/lib/ch_queries/syntax/parser.mli" {"syntax/parser.mli"}
  "_build/install/default/lib/ch_queries/syntax/printer.ml" {"syntax/printer.ml"}
  "_build/install/default/lib/ch_queries/syntax/printer.mli" {"syntax/printer.mli"}
  "_build/install/default/lib/ch_queries/syntax/syntax.ml" {"syntax/syntax.ml"}
  "_build/install/default/lib/ch_queries/syntax/syntax.mli" {"syntax/syntax.mli"}
  "_build/install/default/lib/ch_queries/syntax/ulexer.ml" {"syntax/ulexer.ml"}
  "_build/install/default/lib/ch_queries/syntax/uparser.ml" {"syntax/uparser.ml"}
  "_build/install/default/lib/ch_queries/syntax/uparser.mli" {"syntax/uparser.mli"}
]
libexec: [
  "_build/install/default/lib/ch_queries/ch_queries.cmxs"
  "_build/install/default/lib/ch_queries/ppx/ch_queries_ppx.cmxs" {"ppx/ch_queries_ppx.cmxs"}
  "_build/install/default/lib/ch_queries/ppx/ppx.exe" {"ppx/ppx.exe"}
  "_build/install/default/lib/ch_queries/syntax/ch_queries_syntax.cmxs" {"syntax/ch_queries_syntax.cmxs"}
]
bin: [
  "_build/install/default/bin/ch_queries"
  "_build/install/default/bin/ch_queries_ppx"
]
doc: [
  "_build/install/default/doc/ch_queries/LICENSE"
  "_build/install/default/doc/ch_queries/README.md"
]
